name: Build and Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check
        run: bun run check

      - name: Build
        run: bun run build

      - name: GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile
          tags: ghcr.io/mp281x/${{ github.event.repository.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Dokploy
        run: |
          curl -X POST https://dev.mp281x.xyz/api/application.deploy \
            -H "Content-Type: application/json" \
            -H "x-api-key: ${{ secrets.DOKPLOY_AUTH_TOKEN }}" \
            -d '{"applicationId": "${{ vars.DOKPLOY_APP_ID }}"}'
